# Generated by Django 6.0.3 on 2026-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='accent',
            field=models.CharField(default='#C9A84C', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='color',
            field=models.CharField(default='#162335', max_length=20),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='rrryyt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='gallery',
            name='icon',
            field=models.CharField(default='image', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('consulting', 'Consulting'), ('analytics', 'Analytics'), ('projects', 'Projects'), ('team', 'Team')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
